# action.yml
name: 'Spectacles Lookml validator'
description: 'Validates Lookml with spectacles-ci'
author: 'Louis Racicot'
inputs:
  validator:
    description: 'sql | content | assert | lookml'
    required: true
  lookml_project:
    description: 'The name of the Lookml project'
    required: true
  branch:
    description: 'The git branch to validate in the Lookml project'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.validator }}
    - ${{ inputs.lookml_project }}
    - ${{ inputs.branch }}