# action.yml
name: 'Spectacles Lookml validator'
description: 'Validates Lookml with spectacles-ci'
author: 'Louis Racicot'
inputs:
  validator:
    description: 'Base url of the looker instance'
    required: true
  lookml_project:
    description: 'API3 client_id'
    required: true
  branch:
    description: 'API3 client_secret'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}